/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DriverTrackingRouteImport } from './routes/driver.tracking'
import { Route as PassengerIndexRouteImport } from './routes/passenger.index'
import { Route as ApiPublicGeoapifyHealthRouteImport } from './routes/api/public/geoapify-health'
import { Route as PassengerBusIdRouteImport } from './routes/passenger.bus.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTrackingRoute = DriverTrackingRouteImport.update({
  id: '/driver/tracking',
  path: '/driver/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerIndexRoute = PassengerIndexRouteImport.update({
  id: '/passenger/',
  path: '/passenger/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeoapifyHealthRoute = ApiPublicGeoapifyHealthRouteImport.update({
  id: '/api/public/geoapify-health',
  path: '/api/public/geoapify-health',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerBusIdRoute = PassengerBusIdRouteImport.update({
  id: '/passenger/bus/$id',
  path: '/passenger/bus/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver/tracking': typeof DriverTrackingRoute
  '/driver/': typeof DriverIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/api/public/geoapify-health': typeof ApiPublicGeoapifyHealthRoute
  '/passenger/bus/$id': typeof PassengerBusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver/tracking': typeof DriverTrackingRoute
  '/driver': typeof DriverIndexRoute
  '/passenger': typeof PassengerIndexRoute
  '/api/public/geoapify-health': typeof ApiPublicGeoapifyHealthRoute
  '/passenger/bus/$id': typeof PassengerBusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver/tracking': typeof DriverTrackingRoute
  '/driver/': typeof DriverIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/api/public/geoapify-health': typeof ApiPublicGeoapifyHealthRoute
  '/passenger/bus/$id': typeof PassengerBusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver/tracking'
    | '/driver/'
    | '/passenger/'
    | '/api/public/geoapify-health'
    | '/passenger/bus/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/driver/tracking'
    | '/driver'
    | '/passenger'
    | '/api/public/geoapify-health'
    | '/passenger/bus/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver/tracking'
    | '/driver/'
    | '/passenger/'
    | '/api/public/geoapify-health'
    | '/passenger/bus/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DriverTrackingRoute: typeof DriverTrackingRoute
  DriverIndexRoute: typeof DriverIndexRoute
  PassengerIndexRoute: typeof PassengerIndexRoute
  ApiPublicGeoapifyHealthRoute: typeof ApiPublicGeoapifyHealthRoute
  PassengerBusIdRoute: typeof PassengerBusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/tracking': {
      id: '/driver/tracking'
      path: '/driver/tracking'
      fullPath: '/driver/tracking'
      preLoaderRoute: typeof DriverTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/': {
      id: '/passenger/'
      path: '/passenger'
      fullPath: '/passenger/'
      preLoaderRoute: typeof PassengerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geoapify-health': {
      id: '/api/public/geoapify-health'
      path: '/api/public/geoapify-health'
      fullPath: '/api/public/geoapify-health'
      preLoaderRoute: typeof ApiPublicGeoapifyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/bus/$id': {
      id: '/passenger/bus/$id'
      path: '/passenger/bus/$id'
      fullPath: '/passenger/bus/$id'
      preLoaderRoute: typeof PassengerBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DriverTrackingRoute: DriverTrackingRoute,
  DriverIndexRoute: DriverIndexRoute,
  PassengerIndexRoute: PassengerIndexRoute,
  ApiPublicGeoapifyHealthRoute: ApiPublicGeoapifyHealthRoute,
  PassengerBusIdRoute: PassengerBusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
