/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassengerIndexRouteImport } from './routes/passenger.index'
import { Route as PassengerBusIdRouteImport } from './routes/passenger.bus.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerIndexRoute = PassengerIndexRouteImport.update({
  id: '/passenger/',
  path: '/passenger/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerBusIdRoute = PassengerBusIdRouteImport.update({
  id: '/passenger/bus/$id',
  path: '/passenger/bus/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/passenger/bus/$id': typeof PassengerBusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/passenger': typeof PassengerIndexRoute
  '/passenger/bus/$id': typeof PassengerBusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/passenger/bus/$id': typeof PassengerBusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/passenger/' | '/passenger/bus/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/passenger' | '/passenger/bus/$id'
  id: '__root__' | '/' | '/passenger/' | '/passenger/bus/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PassengerIndexRoute: typeof PassengerIndexRoute
  PassengerBusIdRoute: typeof PassengerBusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/': {
      id: '/passenger/'
      path: '/passenger'
      fullPath: '/passenger/'
      preLoaderRoute: typeof PassengerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/bus/$id': {
      id: '/passenger/bus/$id'
      path: '/passenger/bus/$id'
      fullPath: '/passenger/bus/$id'
      preLoaderRoute: typeof PassengerBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PassengerIndexRoute: PassengerIndexRoute,
  PassengerBusIdRoute: PassengerBusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
